# Generated by Django 4.1.6 on 2023-02-09 23:05

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('texture_ratings', django.contrib.postgres.fields.hstore.HStoreField()),
                ('scent_ratings', django.contrib.postgres.fields.hstore.HStoreField()),
                ('sentiment_ratings', django.contrib.postgres.fields.hstore.HStoreField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.brand')),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('user_product_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('custom_notes', models.CharField(max_length=500)),
                ('texture_notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('sticky', 'sticky'), ('smooth', 'smooth'), ('slimy', 'slimy'), ('cakey', 'cakey'), ('rough', 'rough'), ('wet', 'wet')], max_length=15), size=None)),
                ('texture_enjoyment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('pleasant', 'pleasant'), ('unpleasant', 'unpleasant'), ('neutral', 'neutral'), ('overpowering', 'overpowering')], max_length=15), size=None)),
                ('scent_notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('fruity', 'fruity'), ('clean', 'clean'), ('floral', 'floral'), ('sweet', 'sweet')], max_length=15), size=None)),
                ('scent_enjoyment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('pleasant', 'pleasant'), ('unpleasant', 'unpleasant'), ('neutral', 'neutral'), ('overpowering', 'overpowering')], max_length=15), size=None)),
                ('overall_sentiments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('looks wrong', 'looks wrong'), ('looks good', 'looks good'), ('liked', 'liked'), ('disliked', 'disliked'), ('neutral', 'neutral')], max_length=15), size=None)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
